import { NextResponse } from 'next/server';
import { Match } from '@/lib/types';

// Mock data for upcoming matches
const upcomingMatches: Match[] = [
  {
    id: 'upcoming-1',
    sport: 'football',
    homeTeam: {
      id: '9',
      name: 'Chelsea',
      logo: 'https://resources.premierleague.com/premierleague/badges/100/t8.png',
      form: 'WWDLW',
      ranking: 4,
      recentGoals: 9,
      recentConceded: 4,
    },
    awayTeam: {
      id: '10',
      name: 'Arsenal',
      logo: 'https://resources.premierleague.com/premierleague/badges/100/t3.png',
      form: 'WWWWL',
      ranking: 3,
      recentGoals: 13,
      recentConceded: 5,
    },
    status: 'upcoming',
    startTime: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(), // 4 hours from now
    league: 'Premier League',
    venue: 'Stamford Bridge',
  },
  {
    id: 'upcoming-2',
    sport: 'basketball',
    homeTeam: {
      id: '11',
      name: 'Miami Heat',
      logo: 'https://cdn.nba.com/logos/nba/1610612748/primary/L/logo.svg',
      form: 'WLWWW',
      ranking: 6,
      recentGoals: 495,
      recentConceded: 485,
    },
    awayTeam: {
      id: '12',
      name: 'Phoenix Suns',
      logo: 'https://cdn.nba.com/logos/nba/1610612756/primary/L/logo.svg',
      form: 'WWLWL',
      ranking: 7,
      recentGoals: 505,
      recentConceded: 510,
    },
    status: 'upcoming',
    startTime: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(), // 6 hours from now
    league: 'NBA',
    venue: 'FTX Arena',
  },
  {
    id: 'upcoming-3',
    sport: 'football',
    homeTeam: {
      id: '13',
      name: 'Bayern Munich',
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/FC_Bayern_M%C3%BCnchen_logo_%282017%29.svg/200px-FC_Bayern_M%C3%BCnchen_logo_%282017%29.svg.png',
      form: 'WWWWW',
      ranking: 1,
      recentGoals: 18,
      recentConceded: 3,
    },
    awayTeam: {
      id: '14',
      name: 'Borussia Dortmund',
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Borussia_Dortmund_logo.svg/200px-Borussia_Dortmund_logo.svg.png',
      form: 'WLWDW',
      ranking: 2,
      recentGoals: 12,
      recentConceded: 7,
    },
    status: 'upcoming',
    startTime: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(), // Tomorrow
    league: 'Bundesliga',
    venue: 'Allianz Arena',
  },
  {
    id: 'upcoming-4',
    sport: 'basketball',
    homeTeam: {
      id: '15',
      name: 'Brooklyn Nets',
      logo: 'https://cdn.nba.com/logos/nba/1610612751/primary/L/logo.svg',
      form: 'LWWLW',
      ranking: 8,
      recentGoals: 480,
      recentConceded: 490,
    },
    awayTeam: {
      id: '16',
      name: 'Philadelphia 76ers',
      logo: 'https://cdn.nba.com/logos/nba/1610612755/primary/L/logo.svg',
      form: 'WWWDW',
      ranking: 5,
      recentGoals: 515,
      recentConceded: 500,
    },
    status: 'upcoming',
    startTime: new Date(Date.now() + 8 * 60 * 60 * 1000).toISOString(), // 8 hours from now
    league: 'NBA',
    venue: 'Barclays Center',
  },
  {
    id: 'upcoming-5',
    sport: 'football',
    homeTeam: {
      id: '17',
      name: 'PSG',
      logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a7/Paris_Saint-Germain_F.C..svg/200px-Paris_Saint-Germain_F.C..svg.png',
      form: 'WWWLW',
      ranking: 1,
      recentGoals: 14,
      recentConceded: 4,
    },
    awayTeam: {
      id: '18',
      name: 'Marseille',
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Olympique_Marseille_logo.svg/200px-Olympique_Marseille_logo.svg.png',
      form: 'WDLLW',
      ranking: 4,
      recentGoals: 8,
      recentConceded: 9,
    },
    status: 'upcoming',
    startTime: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(), // 2 days from now
    league: 'Ligue 1',
    venue: 'Parc des Princes',
  },
  {
    id: 'upcoming-6',
    sport: 'football',
    homeTeam: {
      id: '19',
      name: 'Juventus',
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Juventus_FC_2017_logo.svg/200px-Juventus_FC_2017_logo.svg.png',
      form: 'DWWWW',
      ranking: 2,
      recentGoals: 11,
      recentConceded: 3,
    },
    awayTeam: {
      id: '20',
      name: 'AC Milan',
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Logo_of_AC_Milan.svg/200px-Logo_of_AC_Milan.svg.png',
      form: 'WLWDW',
      ranking: 3,
      recentGoals: 10,
      recentConceded: 6,
    },
    status: 'upcoming',
    startTime: new Date(Date.now() + 36 * 60 * 60 * 1000).toISOString(), // 1.5 days from now
    league: 'Serie A',
    venue: 'Allianz Stadium',
  },
  {
    id: 'upcoming-7',
    sport: 'cricket',
    homeTeam: {
      id: '21',
      name: 'New Zealand',
      logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/3/35/New_Zealand_Cricket_Logo.svg/200px-New_Zealand_Cricket_Logo.svg.png',
      form: 'WWLWW',
      ranking: 4,
      recentGoals: 1420,
      recentConceded: 1380,
    },
    awayTeam: {
      id: '22',
      name: 'South Africa',
      logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Cricket_South_Africa_Logo.svg/200px-Cricket_South_Africa_Logo.svg.png',
      form: 'WLWDW',
      ranking: 6,
      recentGoals: 1350,
      recentConceded: 1370,
    },
    status: 'upcoming',
    startTime: new Date(Date.now() + 12 * 60 * 60 * 1000).toISOString(), // 12 hours from now
    league: 'T20 World Cup',
    venue: 'Eden Park',
  },
  {
    id: 'upcoming-8',
    sport: 'cricket',
    homeTeam: {
      id: '23',
      name: 'West Indies',
      logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9b/Cricket_West_Indies_Logo.svg/200px-Cricket_West_Indies_Logo.svg.png',
      form: 'LWLLW',
      ranking: 8,
      recentGoals: 1280,
      recentConceded: 1420,
    },
    awayTeam: {
      id: '24',
      name: 'Sri Lanka',
      logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e8/Sri_Lanka_Cricket_Logo.svg/200px-Sri_Lanka_Cricket_Logo.svg.png',
      form: 'WDWLW',
      ranking: 7,
      recentGoals: 1310,
      recentConceded: 1330,
    },
    status: 'upcoming',
    startTime: new Date(Date.now() + 20 * 60 * 60 * 1000).toISOString(), // 20 hours from now
    league: 'ODI Championship',
    venue: 'Kensington Oval',
  },
  {
    id: 'upcoming-9',
    sport: 'football',
    homeTeam: {
      id: '25',
      name: 'Atletico Madrid',
      logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/d/da/Atletico_Madrid_2012.svg/200px-Atletico_Madrid_2012.svg.png',
      form: 'WWLWD',
      ranking: 2,
      recentGoals: 10,
      recentConceded: 4,
    },
    awayTeam: {
      id: '26',
      name: 'Valencia',
      logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/ce/Valencia_CF.svg/200px-Valencia_CF.svg.png',
      form: 'WDLWL',
      ranking: 7,
      recentGoals: 7,
      recentConceded: 8,
    },
    status: 'upcoming',
    startTime: new Date(Date.now() + 14 * 60 * 60 * 1000).toISOString(),
    league: 'La Liga',
    venue: 'Wanda Metropolitano',
  },
  {
    id: 'upcoming-10',
    sport: 'football',
    homeTeam: {
      id: '27',
      name: 'RB Leipzig',
      logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/04/RB_Leipzig_2014_logo.svg/200px-RB_Leipzig_2014_logo.svg.png',
      form: 'WWWLW',
      ranking: 3,
      recentGoals: 13,
      recentConceded: 5,
    },
    awayTeam: {
      id: '28',
      name: 'Eintracht Frankfurt',
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Eintracht_Frankfurt_Logo.svg/200px-Eintracht_Frankfurt_Logo.svg.png',
      form: 'WLWDW',
      ranking: 5,
      recentGoals: 10,
      recentConceded: 9,
    },
    status: 'upcoming',
    startTime: new Date(Date.now() + 28 * 60 * 60 * 1000).toISOString(),
    league: 'Bundesliga',
    venue: 'Red Bull Arena',
  },
  {
    id: 'upcoming-11',
    sport: 'football',
    homeTeam: {
      id: '29',
      name: 'Monaco',
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/AS_Monaco_FC_logo.svg/200px-AS_Monaco_FC_logo.svg.png',
      form: 'WWLWL',
      ranking: 2,
      recentGoals: 11,
      recentConceded: 7,
    },
    awayTeam: {
      id: '30',
      name: 'Lille',
      logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/6/6d/LOSC_Lille_logo.svg/200px-LOSC_Lille_logo.svg.png',
      form: 'WDWWL',
      ranking: 5,
      recentGoals: 9,
      recentConceded: 6,
    },
    status: 'upcoming',
    startTime: new Date(Date.now() + 32 * 60 * 60 * 1000).toISOString(),
    league: 'Ligue 1',
    venue: 'Stade Louis II',
  },
  {
    id: 'upcoming-12',
    sport: 'football',
    homeTeam: {
      id: '31',
      name: 'Lazio',
      logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/ce/S.S._Lazio_badge.svg/200px-S.S._Lazio_badge.svg.png',
      form: 'WWLWD',
      ranking: 5,
      recentGoals: 12,
      recentConceded: 7,
    },
    awayTeam: {
      id: '32',
      name: 'Roma',
      logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f7/AS_Roma_logo_%282017%29.svg/200px-AS_Roma_logo_%282017%29.svg.png',
      form: 'WDWLW',
      ranking: 6,
      recentGoals: 10,
      recentConceded: 8,
    },
    status: 'upcoming',
    startTime: new Date(Date.now() + 40 * 60 * 60 * 1000).toISOString(),
    league: 'Serie A',
    venue: 'Stadio Olimpico',
  },
  {
    id: 'upcoming-13',
    sport: 'football',
    homeTeam: {
      id: '33',
      name: 'Newcastle',
      logo: 'https://resources.premierleague.com/premierleague/badges/100/t4.png',
      form: 'WWDWL',
      ranking: 7,
      recentGoals: 12,
      recentConceded: 6,
    },
    awayTeam: {
      id: '34',
      name: 'Aston Villa',
      logo: 'https://resources.premierleague.com/premierleague/badges/100/t7.png',
      form: 'WLWWW',
      ranking: 8,
      recentGoals: 11,
      recentConceded: 7,
    },
    status: 'upcoming',
    startTime: new Date(Date.now() + 50 * 60 * 60 * 1000).toISOString(),
    league: 'Premier League',
    venue: 'St James Park',
  },
  {
    id: 'upcoming-14',
    sport: 'football',
    homeTeam: {
      id: '35',
      name: 'Villarreal',
      logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f8/Villarreal_CF.svg/200px-Villarreal_CF.svg.png',
      form: 'WDWLW',
      ranking: 6,
      recentGoals: 9,
      recentConceded: 7,
    },
    awayTeam: {
      id: '36',
      name: 'Real Sociedad',
      logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f6/Real_Sociedad_team_logo.svg/200px-Real_Sociedad_team_logo.svg.png',
      form: 'LWWDW',
      ranking: 4,
      recentGoals: 10,
      recentConceded: 6,
    },
    status: 'upcoming',
    startTime: new Date(Date.now() + 60 * 60 * 60 * 1000).toISOString(),
    league: 'La Liga',
    venue: 'Estadio de la Ceramica',
  },
  {
    id: 'upcoming-15',
    sport: 'football',
    homeTeam: {
      id: '37',
      name: 'Wolfsburg',
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Logo-VfL-Wolfsburg.svg/200px-Logo-VfL-Wolfsburg.svg.png',
      form: 'WLWLW',
      ranking: 6,
      recentGoals: 8,
      recentConceded: 8,
    },
    awayTeam: {
      id: '38',
      name: 'Union Berlin',
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/1._FC_Union_Berlin_Logo.svg/200px-1._FC_Union_Berlin_Logo.svg.png',
      form: 'DWLWW',
      ranking: 7,
      recentGoals: 9,
      recentConceded: 10,
    },
    status: 'upcoming',
    startTime: new Date(Date.now() + 70 * 60 * 60 * 1000).toISOString(),
    league: 'Bundesliga',
    venue: 'Volkswagen Arena',
  },
  {
    id: 'upcoming-16',
    sport: 'football',
    homeTeam: {
      id: '39',
      name: 'Nice',
      logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a4/OGC_Nice_logo.svg/200px-OGC_Nice_logo.svg.png',
      form: 'WWDLW',
      ranking: 6,
      recentGoals: 10,
      recentConceded: 7,
    },
    awayTeam: {
      id: '40',
      name: 'Lens',
      logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/53/RC_Lens_logo.svg/200px-RC_Lens_logo.svg.png',
      form: 'WLWWL',
      ranking: 3,
      recentGoals: 11,
      recentConceded: 8,
    },
    status: 'upcoming',
    startTime: new Date(Date.now() + 80 * 60 * 60 * 1000).toISOString(),
    league: 'Ligue 1',
    venue: 'Allianz Riviera',
  },
  {
    id: 'upcoming-17',
    sport: 'football',
    homeTeam: {
      id: '41',
      name: 'Atalanta',
      logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/6/66/AtalantaBC.svg/200px-AtalantaBC.svg.png',
      form: 'WWWLW',
      ranking: 7,
      recentGoals: 15,
      recentConceded: 8,
    },
    awayTeam: {
      id: '42',
      name: 'Fiorentina',
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/ACF_Fiorentina.svg/200px-ACF_Fiorentina.svg.png',
      form: 'WDLWW',
      ranking: 8,
      recentGoals: 11,
      recentConceded: 9,
    },
    status: 'upcoming',
    startTime: new Date(Date.now() + 90 * 60 * 60 * 1000).toISOString(),
    league: 'Serie A',
    venue: 'Gewiss Stadium',
  },
];

export async function GET() {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 300));

  return NextResponse.json({
    success: true,
    data: upcomingMatches,
    timestamp: new Date().toISOString(),
  });
}
